### ISSUE TITLE
[镜像请求] leopard.sh

### ISSUE THREAD

**Issue by basiczombie-47** [NYIST-CIPS/issues#10]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/NYIST-CIPS/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/NYIST-CIPS/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/NYIST-CIPS/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/NYIST-CIPS/issues/issues/741).

### 项目名称与简介 (Project introduction)

一个给powerpc mac老电脑用的包管理器，提供了许多常用软件包，解决了老电脑编译过慢的问题

### 上游地址与镜像方法 (How to mirror)

项目地址：https://leopard.sh
同步地址：rsync://leopard.sh::html

### 镜像大小 (Mirror size)

约25G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] CIPS - https://mirror.nyist.edu.cn

**Comment by Palvef** [comment]
抱歉，您所提到的项目我们暂时无法进行镜像，请寻找其他镜像站予以支持，感谢您提交镜像申请，祝好
