### ISSUE TITLE
ubuntu源出现问题

### ISSUE THREAD

**Issue by luoyueyuguang** [NYIST-CIPS/issues#11]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/NYIST-CIPS/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/NYIST-CIPS/issues/issues).

### 发生了什么（What happened）

ubuntu源出现了问题, https://mirror.nyist.edu.cn/ubuntu/ 点进去为空，`sudo apt update`出现了问题,报错如下
```
Ign:1 https://mirror.nyist.edu.cn/ubuntu focal InRelease
Ign:2 https://mirror.nyist.edu.cn/ubuntu focal-updates InRelease
Ign:3 https://mirror.nyist.edu.cn/ubuntu focal-backports InRelease
Err:4 https://mirror.nyist.edu.cn/ubuntu focal Release 
  404  Not Found [IP: 222.139.215.198 443]
Err:5 https://mirror.nyist.edu.cn/ubuntu focal-updates Release
  404  Not Found [IP: 222.139.215.198 443]
Err:6 https://mirror.nyist.edu.cn/ubuntu focal-backports Release
  404  Not Found [IP: 222.139.215.198 443]
```

### 期望的现象（What you expected to happen）

ubuntu源被修复，https://mirror.nyist.edu.cn/ubuntu/不为空，可以正常使用。

### 如何重现此问题（How to reproduce it）

将镜像源更换为nyist的源，或点击https://mirror.nyist.edu.cn/ubuntu/

### 操作系统（OS Version）

Ubuntu 20.04.6 LTS

**Comment by Palvef** [comment]
已解决
