### ISSUE TITLE
[cips]Mirror Request for new mirror images

### ISSUE THREAD

**Issue by nanosunny** [NYIST-CIPS/issues#12]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/NYIST-CIPS/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/NYIST-CIPS/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/NYIST-CIPS/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/NYIST-CIPS/issues/issues/741).

### 项目名称与简介 (Project introduction)

资源没有了，lxc无法lauch

### 上游地址与镜像方法 (How to mirror)

资源没有了，lxc无法lauch

### 镜像大小 (Mirror size)

6

### 备注 (Note)

1

### 期望上线的镜像站 (Expected mirroring sites)

- [X] CIPS - https://mirror.nyist.edu.cn

**Comment by Palvef** [comment]
没有理解您的意思
