### ISSUE TITLE
[镜像请求] 

### ISSUE THREAD

**Issue by fenshezhuiyi** [NYIST-CIPS/issues#9]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/NYIST-CIPS/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/NYIST-CIPS/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/NYIST-CIPS/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/NYIST-CIPS/issues/issues/741).

### 项目名称与简介 (Project introduction)

openKylin 社区是在开源、自愿、平等和协作的基础上，由基础软硬件企业、非营利性组织、社团组织、高等院校、科研机构和个人开发者共同创立的一个开源社区，致力于通过开源、开放的社区合作，构建桌面操作系统开源社区，推动Linux开源技术及其软硬件生态繁荣发展。 ​
官网地址：https://www.openkylin.top/

### 上游地址与镜像方法 (How to mirror)

官方源仓库网址：[https://archive.openkylin.top/](https://archive.openkylin.top/) 
官方镜像库网址：[https://releases.openkylin.top/](https://releases.openkylin.top/)  

### 镜像大小 (Mirror size)

120G

### 期望上线的镜像站 (Expected mirroring sites)

- [X] CIPS - https://mirror.nyist.edu.cn

**Comment by Palvef** [comment]
您好，首先感谢您提交镜像申请，但经过运维综合考虑，且服务器资源有限，我们暂不考虑镜像OpenKyin项目。
